image: clojure:tools-deps

services:
  - docker:dind

cache: &global_cache
  key: ${CI_JOB_NAME}
  paths:
    - node_modules/
    - .m2
    - .yarn

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

cljs-test:
  image: ghcr.io/schnaq/clojure-yarn-chrome
  before_script:
    - yarn install --non-interactive --frozen-lockfile
    - clojure -Sdeps '{:mvn/local-repo ".m2"}' -M:dev -m "shadow.cljs.devtools.cli" compile ci-tests
  script:
    - yarn karma start --single-run --reporters junit
  artifacts:
    when: always
    reports:
      junit: target/TESTS.xml

clj-test:
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - .m2
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y git
  script:
    - clojure -J-Dguardrails.enabled=true -Sdeps '{:mvn/local-repo ".m2"}' -M:dev:clj-tests --profile :ci
  artifacts:
    when: always
    reports:
      junit: junit.xml

build_latest_images:
  needs: [ "clj-test", "cljs-test" ]
  image: docker
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
